const fs = require('fs');
const path = require('path');

// Translation map for api-docs.html
const apiDocsTranslations = [
    // Quickstart section
    ['⚡ Быстрый старт', '⚡ Quick Start'],
    ['Начните использовать API за несколько минут. Выберите ваш любимый язык или инструмент:', 'Start using the API in just a few minutes. Choose your favorite language or tool:'],
    ['Отправьте первый запрос к модели', 'Send your first request to a model'],
    ['Получить API ключ', 'Get API Key'],
    ['Настройте аутентификацию', 'Set up authentication'],
    ['Получайте ответы в реальном времени', 'Get responses in real time'],
    ['Ваш первый запрос', 'Your First Request'],
    ['Вот минимальный пример отправки сообщения модели:', 'Here\'s a minimal example of sending a message to a model:'],
    ['Копировать', 'Copy'],
    ['Ты полезный ассистент.', 'You are a helpful assistant.'],
    ['Привет! Расскажи о себе.', 'Hello! Tell me about yourself.'],
    // Authentication section
    ['🔑 Аутентификация', '🔑 Authentication'],
    ['Все запросы к API требуют аутентификации через API ключ. Ключ передается в заголовке', 'All API requests require authentication via an API key. The key is passed in the'],
    ['Замените', 'Replace'],
    ['на ваш реальный API ключ от провайдера.', 'with your actual API key from the provider.'],
    ['Получение API ключей', 'Getting API Keys'],
    ['Каждый провайдер имеет свой способ получения API ключа:', 'Each provider has its own way of obtaining an API key:'],
    ['Провайдер', 'Provider'],
    ['Где получить ключ', 'Where to get a key'],
    ['Формат ключа', 'Key format'],
    ['⚠️ Безопасность', '⚠️ Security'],
    ['Никогда не храните API ключи в клиентском коде. Используйте переменные окружения или серверные прокси для production приложений.', 'Never store API keys in client-side code. Use environment variables or server proxies for production applications.'],
    ['Импорт и экспорт ключей', 'Import and Export Keys'],
    ['В настройках (вкладка «Провайдеры») доступны кнопки для массового управления ключами:', 'In settings (the "Providers" tab), buttons are available for bulk key management:'],
    ['Импорт ключей (.txt)', 'Import Keys (.txt)'],
    ['— загрузите файл с ключами, все провайдеры за раз', '— upload a file with keys, all providers at once'],
    ['Экспорт ключей', 'Export Keys'],
    ['— скачайте все ключи в файл', '— download all keys to a file'],
    ['Удалить все ключи', 'Delete All Keys'],
    ['— очистить все ключи одним кликом (с подтверждением)', '— clear all keys in one click (with confirmation)'],
    ['Формат файла для импорта', 'Import File Format'],
    ['Правила:', 'Rules:'],
    ['Каждый ключ на новой строке', 'Each key on a new line'],
    ['(разделитель — пробел, дефис, пробел)', '(separator — space, dash, space)'],
    ['Порядок строк не важен', 'Line order does not matter'],
    ['Не все ключи обязательны — можно указать только нужные', 'Not all keys are required — you can specify only the ones you need'],
    ['игнорируются (комментарии)', 'are ignored (comments)'],
    ['Название в файле', 'Name in file'],
    ['💬 Chat Completions', '💬 Chat Completions'],
    ['Создает ответ модели для заданного разговора.', 'Creates a model response for a given conversation.'],
    ['Параметры запроса', 'Request Parameters'],
    ['Обязательный', 'Required'],
    ['Опциональный', 'Optional'],
    ['ID модели для использования. Например:', 'ID of the model to use. For example:'],
    ['Список сообщений, представляющих разговор. Каждый объект содержит', 'List of messages representing a conversation. Each object contains'],
    ['и', 'and'],
    ['Температура выборки от 0 до 2. Более высокие значения делают ответы более случайными. По умолчанию: 1', 'Sampling temperature from 0 to 2. Higher values make responses more random. Default: 1'],
    ['Максимальное количество токенов в ответе. По умолчанию: модель-зависимое', 'Maximum number of tokens in the response. Default: model-dependent'],
    ['Включить потоковую передачу ответа. По умолчанию: false', 'Enable streaming response. Default: false'],
    ['Формат ответа. Используйте', 'Response format. Use'],
    ['для JSON mode', 'for JSON mode'],
    ['Структура сообщений', 'Message Structure'],
    ['Каждое сообщение в массиве', 'Each message in the'],
    ['содержит:', 'array contains:'],
    ['Роль', 'Role'],
    ['Описание', 'Description'],
    ['Системный промпт, задающий поведение модели', 'System prompt that sets model behavior'],
    ['Сообщение от пользователя', 'Message from the user'],
    ['Предыдущий ответ модели (для контекста)', 'Previous model response (for context)'],
    ['Пример ответа', 'Example Response'],
    ['Привет! Я языковая модель, разработанная OpenAI...', 'Hello! I am a language model developed by OpenAI...'],
    ['📋 List Models', '📋 List Models'],
    ['Возвращает список всех доступных моделей.', 'Returns a list of all available models.'],
    ['Не требует параметров. Возвращает список всех моделей, доступных для вашего API ключа.', 'Requires no parameters. Returns a list of all models available for your API key.'],
    ['Пример запроса', 'Example Request'],
    ['🔍 Retrieve Model', '🔍 Retrieve Model'],
    ['Возвращает информацию о конкретную модель.', 'Returns information about a specific model.'],
    ['Параметры пути', 'Path Parameters'],
    ['ID модели. Например:', 'Model ID. For example:'],
    ['⚡ Streaming', '⚡ Streaming'],
    ['Потоковая передача позволяет получать ответ модели по мере его генерации, улучшая воспринимаемую скорость ответа.', 'Streaming allows receiving the model\'s response as it is generated, improving perceived response speed.'],
    ['💡 Когда использовать streaming', '💡 When to use streaming'],
    ['Используйте streaming для длинных ответов или когда важно показать пользователю прогресс генерации в реальном времени.', 'Use streaming for long responses or when it\'s important to show the user real-time generation progress.'],
    ['Включение streaming', 'Enabling Streaming'],
    ['Добавьте параметр', 'Add the parameter'],
    ['в запрос:', 'to the request:'],
    ['Расскажи длинную историю', 'Tell me a long story'],
    ['Формат SSE ответа', 'SSE Response Format'],
    ['Каждый chunk приходит в формате Server-Sent Events:', 'Each chunk arrives in Server-Sent Events format:'],
    ['❌ Ошибки', '❌ Errors'],
    ['API использует стандартные HTTP коды ошибок. При возникновении ошибки тело ответа содержит детальное описание.', 'The API uses standard HTTP error codes. When an error occurs, the response body contains a detailed description.'],
    ['Код', 'Code'],
    ['Решение', 'Solution'],
    ['Проверьте формат запроса и параметры', 'Check the request format and parameters'],
    ['Проверьте API ключ', 'Check the API key'],
    ['Нет доступа к запрашиваемому ресурсу', 'No access to the requested resource'],
    ['Проверьте URL и ID модели', 'Check the URL and model ID'],
    ['Превышен лимит запросов. Подождите и повторите', 'Rate limit exceeded. Wait and retry'],
    ['Ошибка на стороне сервера. Повторите позже', 'Server-side error. Try again later'],
    ['Сервис временно недоступен', 'Service temporarily unavailable'],
    ['Формат ошибки', 'Error Format'],
    ['Retry логика', 'Retry Logic'],
    ['✅ Best Practice', '✅ Best Practice'],
    ['При получении ошибки 429 (Rate Limit) или 5xx (Server Error), используйте exponential backoff: ждите 1 секунду, затем 2, 4, 8... Максимум 5 попыток.', 'When receiving a 429 (Rate Limit) or 5xx (Server Error) error, use exponential backoff: wait 1 second, then 2, 4, 8... Maximum 5 attempts.'],
    ['⏱️ Rate Limits', '⏱️ Rate Limits'],
    ['Лимиты запросов зависят от провайдера и вашего тарифного плана. Информация о лимитах передается в заголовках ответа.', 'Request limits depend on the provider and your pricing plan. Limit information is transmitted in response headers.'],
    ['Заголовки ответа', 'Response Headers'],
    ['Заголовок', 'Header'],
    ['Максимальное количество запросов в период', 'Maximum number of requests per period'],
    ['Оставшееся количество запросов', 'Remaining number of requests'],
    ['Время сброса лимита (RFC 7231)', 'Limit reset time (RFC 7231)'],
    ['Максимальное количество токенов в период', 'Maximum number of tokens per period'],
    ['Оставшееся количество токенов', 'Remaining number of tokens'],
    ['Лимиты по провайдерам (бесплатные планы)', 'Provider Limits (Free Plans)'],
    ['Запросов/мин', 'Requests/min'],
    ['Токенов/мин', 'Tokens/min'],
    ['Зависит от модели', 'Model-dependent'],
    ['🔌 Провайдеры', '🔌 Providers'],
    ['Multi-LLM поддерживает широкий спектр провайдеров. Все они используют единый формат API.', 'Multi-LLM supports a wide range of providers. They all use a unified API format.'],
    ['Поддерживаемые провайдеры', 'Supported Providers'],
    ['Базовые URL', 'Base URLs'],
    ['💡 Локальные модели', '💡 Local Models'],
    ['Для использования локальных моделей через Ollama или LM Studio запустите соответствующий сервер и укажите его адрес в настройках.', 'To use local models via Ollama or LM Studio, start the appropriate server and specify its address in settings.'],
    ['🤗 Hugging Face Inference API', '🤗 Hugging Face Inference API'],
    ['Hugging Face предоставляет доступ к тысячам открытых моделей через единый облачный API. Формат запросов совместим с OpenAI API.', 'Hugging Face provides access to thousands of open models through a unified cloud API. The request format is compatible with the OpenAI API.'],
    ['Пример запроса к HF', 'Example HF Request'],
    ['Привет!', 'Hello!'],
    ['Популярные модели на HF Hub', 'Popular Models on HF Hub'],
    ['Модель', 'Model'],
    ['Параметры', 'Parameters'],
    ['⚠️ Бесплатный тариф HF', '⚠️ Free HF Plan'],
    ['Бесплатный Inference API имеет ограничения: крупные модели могут быть недоступны или работать медленно. Для стабильного использования рассмотрите', 'The free Inference API has limitations: large models may be unavailable or work slowly. For stable usage, consider'],
    ['или Serverless Inference.', 'or Serverless Inference.'],
    ['🔀 OpenRouter', '🔀 OpenRouter'],
    ['OpenRouter — агрегатор API, предоставляющий доступ к 300+ моделям от разных провайдеров через единый интерфейс, совместимый с OpenAI API. Один ключ — все модели.', 'OpenRouter is an API aggregator providing access to 300+ models from different providers through a unified interface compatible with the OpenAI API. One key — all models.'],
    ['Пример запроса к OpenRouter', 'Example OpenRouter Request'],
    ['Преимущества OpenRouter', 'OpenRouter Advantages'],
    ['Один API ключ для доступа к моделям от OpenAI, Anthropic, Google, Meta, Mistral и других', 'One API key to access models from OpenAI, Anthropic, Google, Meta, Mistral and others'],
    ['Автоматический fallback между провайдерами', 'Automatic fallback between providers'],
    ['Единый биллинг и отслеживание расходов', 'Unified billing and expense tracking'],
    ['Бесплатные модели доступны без привязки карты', 'Free models available without card binding'],
    ['Популярные модели на OpenRouter', 'Popular Models on OpenRouter'],
    ['💡 Полный список моделей', '💡 Full Model List'],
    ['Актуальный список из 300+ моделей доступен на', 'An up-to-date list of 300+ models is available at'],
    ['. В приложении список загружается автоматически при проверке API ключа.', '. In the application, the list is loaded automatically when checking the API key.'],
    ['← Вернуться к приложению', '← Return to Application'],
    ['Multi-LLM API Документация v1.0', 'Multi-LLM API Documentation v1.0'],
    ['Скопировано!', 'Copied!'],
];

// Translation map for LLM_Compare.html
const mainHtmlTranslations = [
    ['Multi-LLM + Синтез', 'Multi-LLM + Synthesis'],
    ['Ручной режим: копируйте промты → вставляйте ответы → получайте результат', 'Manual mode: copy prompts → paste responses → get results'],
    ['Сохранено', 'Saved'],
    ['API Документация', 'API Documentation'],
    ['История запросов', 'Request History'],
    ['История', 'History'],
    ['Переключить тему', 'Toggle theme'],
    ['Настройки', 'Settings'],
    ['Запрос', 'Request'],
    ['Улучшение', 'Improve'],
    ['Модели', 'Models'],
    ['Синтез', 'Synthesis'],
    ['Результат', 'Result'],
    ['Шаг 1: Ваш сырой запрос', 'Step 1: Your Raw Request'],
    ['Введите ваш исходный вопрос или задачу', 'Enter your original question or task'],
    ['Например: Как работает квантовая запутанность?', 'For example: How does quantum entanglement work?'],
    ['Далее: Улучшение', 'Next: Improve'],
    ['Системный промт для улучшения', 'System Prompt for Improvement'],
    ['1. Скопируйте этот системный промт', '1. Copy this system prompt'],
    ['Скопировать системный промт', 'Copy system prompt'],
    ['Промт для отправки', 'Prompt to Send'],
    ['2. Скопируйте и отправьте вместе с системным промтом', '2. Copy and send along with the system prompt'],
    ['Скопировать промт для улучшения', 'Copy improvement prompt'],
    ['Отправить в провайдера', 'Send to Provider'],
    ['Отправить в ИИ', 'Send to AI'],
    ['Локальный ИИ', 'Local AI'],
    ['Отправить в Hugging Face', 'Send to Hugging Face'],
    ['Отправить в HF', 'Send to HF'],
    ['Заполнено ИИ', 'Filled by AI'],
    ['3. Вставьте улучшенный промт', '3. Paste the improved prompt'],
    ['Вставьте сюда ответ от ИИ (улучшенный промт)', 'Paste the AI response here (improved prompt)'],
    ['Вставьте улучшенный промт сюда...', 'Paste improved prompt here...'],
    ['Назад', 'Back'],
    ['Далее: Модели', 'Next: Models'],
    ['Улучшенный промт для отправки в модели', 'Improved prompt to send to models'],
    ['Отправьте этот промт в каждую модель ниже', 'Send this prompt to each model below'],
    ['Скопировать улучшенный промт', 'Copy improved prompt'],
    ['Далее: Синтез', 'Next: Synthesis'],
    ['Системный промт для агрегации', 'System Prompt for Aggregation'],
    ['Скопировать системный промт для агрегации', 'Copy aggregation system prompt'],
    ['Промт с ответами моделей', 'Prompt with Model Responses'],
    ['Скопировать промт для агрегации', 'Copy aggregation prompt'],
    ['3. Вставьте синтезированный ответ', '3. Paste the synthesized response'],
    ['Вставьте сюда финальный агрегированный ответ', 'Paste the final aggregated answer here'],
    ['Вставьте синтезированный ответ...', 'Paste synthesized response...'],
    ['Далее: Результат', 'Next: Result'],
    ['Финальный ответ', 'Final Answer'],
    ['Сравнение', 'Comparison'],
    ['Синтезированный ответ', 'Synthesized Response'],
    ['Скопировать финальный ответ', 'Copy final answer'],
    ['Сравнение ответов моделей', 'Model Responses Comparison'],
    ['Средняя оценка', 'Average rating'],
    ['Итоговый JSON', 'Final JSON'],
    ['Скопировать JSON', 'Copy JSON'],
    ['Продолжить чат', 'Continue Chat'],
    ['Новый запрос', 'New Request'],
    ['Общие', 'General'],
    ['Промты', 'Prompts'],
    ['Шаблоны', 'Templates'],
    ['Провайдеры', 'Providers'],
    ['Логи', 'Logs'],
    ['Профиль задачи', 'Task Profile'],
    ['Профиль меняет системные промты для улучшения и синтеза. Если вы вручную измените промты, профиль автоматически станет', 'The profile changes system prompts for improvement and synthesis. If you manually change prompts, the profile will automatically become'],
    ['Активный профиль', 'Active Profile'],
    ['Универсальный', 'Universal'],
    ['Сбалансированный режим для большинства задач.', 'Balanced mode for most tasks.'],
    ['Системные уведомления', 'System Notifications'],
    ['Показывать индикатор автосохранения и неблокирующие предупреждения.', 'Show auto-save indicator and non-blocking warnings.'],
    ['Учитывать оценки в синтезе', 'Use ratings in synthesis'],
    ['Передавать оценки пользователя в агрегирующий промт как мягкий сигнал предпочтения. Если оценка не указана, это считается нейтральным случаем, а не минусом.', 'Pass user ratings to the aggregation prompt as a soft preference signal. If no rating is specified, it is considered neutral rather than a negative.'],
    ['Вернуть умолчания', 'Reset Defaults'],
    ['Удалить выбранные', 'Delete Selected'],
    ['Удалить все', 'Delete All'],
    ['Добавить модель', 'Add Model'],
    ['Название', 'Name'],
    ['GPT', 'GPT'],
    ['OpenAI', 'OpenAI'],
    ['Системный промт (опционально)', 'System Prompt (optional)'],
    ['Оставьте пустым для использования общего промта', 'Leave empty to use the general prompt'],
    ['Ссылка на чат (опционально)', 'Chat URL (optional)'],
    ['Промт для улучшения', 'Improvement Prompt'],
    ['Сбросить', 'Reset'],
    ['Промт для агрегации', 'Aggregation Prompt'],
    ['Сохранённые шаблоны промтов', 'Saved Prompt Templates'],
    ['Шаблоны можно использовать как начальные точки для новых запросов', 'Templates can be used as starting points for new requests'],
    ['Добавить шаблон', 'Add Template'],
    ['Подключить провайдера для автоматической обработки', 'Connect a provider for automatic processing'],
    ['Кнопка «Отправить в ИИ» появится на шагах синтеза и улучшения промта. Если выключено — всё остаётся в ручном режиме.', 'The "Send to AI" button will appear on synthesis and prompt improvement steps. If disabled — everything remains in manual mode.'],
    ['Локальные', 'Local'],
    ['Другой', 'Other'],
    ['Облачные', 'Cloud'],
    ['Ручной ввод', 'Manual input'],
    ['требуется API ключ', 'API key required'],
    ['выбран', 'selected'],
    ['Импорт ключей (.txt)', 'Import Keys (.txt)'],
    ['Экспорт ключей', 'Export Keys'],
    ['Удалить все ключи', 'Delete All Keys'],
    ['Формат .txt', 'Format: .txt'],
    ['каждый ключ с новой строки, порядок не важен', 'each key on a new line, order doesn\'t matter'],
    ['Показать/скрыть', 'Show/hide'],
    ['Ключ хранится только в браузере.', 'Key is stored only in your browser.'],
    ['Адрес сервера', 'Server Address'],
    ['Не подключено', 'Not connected'],
    ['Проверить', 'Test'],
    ['Не проверено', 'Not checked'],
    ['Проверить ключ', 'Test Key'],
    ['Введите API ключ и нажмите «Проверить ключ» для загрузки списка моделей.', 'Enter an API key and click "Test Key" to load the model list.'],
    ['Модель', 'Model'],
    ['Выберите модель из списка.', 'Select a model from the list.'],
    ['Выберите провайдера и проверьте подключение', 'Select a provider and test the connection'],
    ['Обновить', 'Refresh'],
    ['Укажите ID модели вручную.', 'Specify model ID manually.'],
    ['Использовать для', 'Use for'],
    ['Всего сразу', 'Everything'],
    ['Улучшение промта + синтез ответов', 'Prompt improvement + response synthesis'],
    ['Только улучшение промта', 'Prompt improvement only'],
    ['Шаг 2: уточнение вашего запроса', 'Step 2: refining your request'],
    ['Только синтез ответов', 'Response synthesis only'],
    ['Шаг 4: агрегация ответов всех моделей', 'Step 4: aggregation of all model responses'],
    ['Документация API', 'API Documentation'],
    ['Все провайдеры используют формат, совместимый с OpenAI API. Подробности по эндпоинтам, параметрам, стримингу и rate limits — в документации.', 'All providers use a format compatible with the OpenAI API. Details on endpoints, parameters, streaming and rate limits — in the documentation.'],
    ['Открыть документацию API →', 'Open API Documentation →'],
    ['Сохранять логи', 'Save logs'],
    ['При отключении новые записи не сохраняются.', 'When disabled, new entries are not saved.'],
    ['Экспорт', 'Export'],
    ['Очистить логи', 'Clear Logs'],
    ['Всего', 'Total'],
    ['Ошибок', 'Errors'],
    ['Предупреждений', 'Warnings'],
    ['Все', 'All'],
    ['Ошибки', 'Errors'],
    ['Предупреждения', 'Warnings'],
    ['Инфо', 'Info'],
    ['Успех', 'Success'],
    ['Логи пусты', 'Logs are empty'],
    ['Закрыть', 'Close'],
    ['Сохранить', 'Save'],
    ['Продолжить', 'Continue'],
    ['Отмена', 'Cancel'],
    ['Вставьте ссылки на существующие чаты, чтобы ИИ помнил контекст. Можно оставить пустыми — откроются новые чаты.', 'Paste links to existing chats so the AI remembers context. Can be left empty — new chats will open.'],
    ['История пуста', 'History is empty'],
    ['Завершённые сессии появятся здесь', 'Completed sessions will appear here'],
    ['Поиск по истории...', 'Search history...'],
    ['Чат', 'Chat'],
    ['История чата', 'Chat History'],
    ['Развернуть', 'Expand'],
    ['Новый чат', 'New Chat'],
    ['Импортировано ключей', 'Keys imported'],
    ['Нет ключей для экспорта', 'No keys to export'],
    ['Экспортировано ключей', 'Keys exported'],
    ['Удалено ключей', 'Keys deleted'],
    ['Ключей нет', 'No keys'],
    ['Проверка подключения', 'Testing connection'],
    ['Проверка', 'Testing'],
    ['Введите API ключ', 'Enter API key'],
    ['Соединение установлено', 'Connected'],
    ['Ошибка подключения', 'Connection error'],
    ['Неверный API ключ', 'Invalid API key'],
    ['Доступ запрещён', 'Access denied'],
    ['Модели загружены', 'Models loaded'],
    ['Ошибка загрузки моделей', 'Error loading models'],
    ['Логи экспортированы', 'Logs exported'],
    ['Настройки сохранены', 'Settings saved'],
    ['Данные сохранены', 'Data saved'],
    ['Данные загружены', 'Data loaded'],
    ['Данные не найдены', 'Data not found'],
    ['Ошибка загрузки данных', 'Error loading data'],
    ['Ошибка сохранения данных', 'Error saving data'],
    ['Ошибка импорта', 'Import error'],
    ['Ошибка экспорта', 'Export error'],
    ['Не удалось сохранить', 'Failed to save'],
    ['Не удалось загрузить', 'Failed to load'],
    ['Успешно', 'Success'],
    ['Не удалось', 'Failed'],
    ['Ошибка', 'Error'],
    ['Предупреждение', 'Warning'],
    ['Подтверждение', 'Confirmation'],
    ['Вы уверены?', 'Are you sure?'],
    ['Это действие нельзя отменить.', 'This action cannot be undone.'],
    ['Удалить', 'Delete'],
    ['Отменить', 'Cancel'],
    ['Подтвердить', 'Confirm'],
    ['порт', 'port'],
];

function translateFile(filePath, translations) {
    let content = fs.readFileSync(filePath, 'utf8');
    let count = 0;
    for (const [from, to] of translations) {
        let idx = content.indexOf(from);
        while (idx !== -1) {
            content = content.substring(0, idx) + to + content.substring(idx + from.length);
            count++;
            idx = content.indexOf(from, idx + to.length);
        }
    }
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`${path.basename(filePath)}: ${count} replacements made`);
}

// Translate files
translateFile('api-docs.html', apiDocsTranslations);
translateFile('LLM_Compare.html', mainHtmlTranslations);

console.log('Translation complete!');
